#!/bin/bash

# No `if` statement needed just "${1:-default}". 
#Take the first arg (that the meaning of the 1) else set default value (world) in this case.

name="${1:-world}"
log_level="${LOG_LEVEL:-info}"


echo "Hello, $name (log: $log_level)"
