#!/bin/bash

# Process files (*), skip hidden files (.*) ones
for file in * .*; do
    [[ "$file" == .* ]] &&  echo "hidden file $file" && continue
    [[ -f "$file" ]] || continue
    echo "Processing: $file"
done
