#!/bin/bash

# Case transformation

name="hello world"
echo "${name^}"
# Hello world (capitalize first)

echo "${name^^}"
# HELLO WORLD (uppercase all)

name="HELLO WORLD"
echo "${name,,}"
# hello world (lowercase all) 
