#!/bin/bash


# The variable PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

# The colons replaced by newlines for better readability

echo "${PATH//:/$'\n'}"
